### ISSUE TITLE
Android Error: Unsupported device

### ISSUE THREAD

**Issue by jose-staizen** [capacitor-community/text-to-speech#68] opened 2021-06-21 04:31 UTC
**Current behavior:**

Version:
Capacitor v2
TTS 0.2.3

Device:
Android 11
Android 10
Android 9

Whenever I execute the function:
```
const speak = async () => {
  await TextToSpeech.speak({
    text: 'This is a sample text.',
    locale: 'en_US',
    speechRate: 1.0,
    pitchRate: 1.0,
    volume: 1.0,
    category: 'ambient',
  });
};
```
Error output:
```
06-21 03:57:29.328 E/Capacitor/Console(30873): File: https://portal.prosperus.asia/static/js/29.a169ec33.chunk.js - Line 2 - Msg: Uncaught (in promise) Error: Not supported on this device.
```
**Expected behavior:**

TTS should work.

**Steps to reproduce:**

Capacitor v2
TTS 0.2.3 version.

**Other information:**

**Capacitor doctor:**

```
Latest Dependencies:

  @capacitor/cli: 3.0.1    
  @capacitor/core: 3.0.1   
  @capacitor/android: 3.0.1
  @capacitor/electron: 3.0.1
  @capacitor/ios: 3.0.1

Installed Dependencies:

  @capacitor/cli 2.4.7
  @capacitor/ios 2.4.7
  @capacitor/core 2.4.7
  @capacitor/android 2.4.7
  @capacitor/electron not installed

[success] Android looking great!
```

**Comment by robingenz** [comment] 2021-06-21 14:17
Thank you for your request.
This seems to be a duplicate of #62. For this reason, I am closing this issue.
Please check your imports (see this [comment](https://github.com/capacitor-community/text-to-speech/issues/62#issuecomment-814288776)).
Let me know if the problem persists.

**Closed by robingenz** 2021-06-21 14:17 UTC
